name: umeng_push_sdk
description: upush sdk plugin.
version: 2.1.0
homepage: https://www.umeng.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.umeng.message
        pluginClass: UmengPushSdkPlugin
      ios:
        pluginClass: UmengPushSdkPlugin